default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: streaming_video_api_development

test:
  <<: *default
  database: streaming_video_api_test
  
production:
  <<: *default
  database: streaming_video_api_production
  username: streaming_video_api
  password: <%= ENV['STREAMING_VIDEO_API_DATABASE_PASSWORD'] %>
